// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"gorm.io/gorm"
)

const TableNameCategory = "categories"

// Category mapped from table <categories>
type Category struct {
	ID           int64  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name         string `gorm:"column:name;not null" json:"name"`
	Slug         string `gorm:"column:slug;not null" json:"slug"`
	Pid          int64  `gorm:"column:pid;default:0" json:"pid"`
	DisplayOrder int64  `gorm:"column:display_order;default:50" json:"display_order"`
	Description  string `gorm:"column:description" json:"description"`

	CreatedAt *LocalTime      `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt *LocalTime     `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;default:CURRENT_TIMESTAMP" json:"-"`

	Children []*Category `json:"children" gorm:"-"`
}

// TableName Category's table name
func (*Category) TableName() string {
	return TableNameCategory
}
