// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNamePersonalAccessToken = "personal_access_tokens"

// PersonalAccessToken mapped from table <personal_access_tokens>
type PersonalAccessToken struct {
	ID            int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	TokenableType string    `gorm:"column:tokenable_type;not null" json:"tokenable_type"`
	TokenableID   int64     `gorm:"column:tokenable_id;not null" json:"tokenable_id"`
	Name          string    `gorm:"column:name;not null" json:"name"`
	Token         string    `gorm:"column:token;not null" json:"token"`
	Abilities     string    `gorm:"column:abilities" json:"abilities"`
	LastUsedAt    time.Time `gorm:"column:last_used_at" json:"last_used_at"`
	ExpiresAt     time.Time `gorm:"column:expires_at" json:"expires_at"`
	CreatedAt     time.Time `gorm:"column:created_at" json:"created_at"`
	UpdatedAt     time.Time `gorm:"column:updated_at" json:"updated_at"`
}

// TableName PersonalAccessToken's table name
func (*PersonalAccessToken) TableName() string {
	return TableNamePersonalAccessToken
}
