// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"github.com/guregu/null/v5"
	"gorm.io/gorm"
)

const TableNameProduct = "products"

// Product mapped from table <products>
type Product struct {
	ID              int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	ModelNO         string         `gorm:"column:model_no;not null" json:"model_no" binding:"required"`
	FrameMaterialID int64          `gorm:"column:frame_material_id;" json:"frame_material_id"`
	LensWidth       float32        `gorm:"column:lens_width;" json:"lens_width"`
	NoseBridge      float32        `gorm:"column:nose_bridge;" json:"nose_bridge"`
	TempleLength    float32        `gorm:"column:temple_length;" json:"temple_length"`
	Title           string         `gorm:"column:title;" json:"title"`
	SkuCount        int64          `gorm:"column:sku_count;default:0" json:"sku_count"`
	Description     string         `gorm:"column:description" json:"description"`
	CategoryID      int64          `gorm:"column:category_id" json:"category_id" binding:"required"`
	SeriesID        null.Int64     `gorm:"column:series_id;" json:"series_id"`
	BrandID         null.Int64     `gorm:"column:brand_id;" json:"brand_id"`
	ItemCode        null.String    `gorm:"column:item_code;" json:"item_code"`
	Gender          null.String    `gorm:"column:gender" json:"gender"`
	CreatedAt       *LocalTime     `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt       *LocalTime      `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"`
	DeletedAt       gorm.DeletedAt `gorm:"column:deleted_at;default:CURRENT_TIMESTAMP" json:"-"`

	ImageURLs []string `json:"image_urls" gorm:"-"` // 添加这个字段来存储主图 URL 列表
	CategoryPath []int   `json:"category_path" gorm:"-"` // 使用 gorm:"-" 表示这不是数据库字段

	// 添加关联关系
	Series          *Series         `json:"series" gorm:"foreignKey:SeriesID"`
	Category        *Category       `json:"category" gorm:"foreignKey:CategoryID"`
	Brand           *Brand          `json:"brand" gorm:"foreignKey:BrandID"`
	FrameMaterial   *FrameMaterial  `json:"frame_material" gorm:"foreignKey:FrameMaterialID"`
}

// TableName Product's table name
func (*Product) TableName() string {
	return TableNameProduct
}
