// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"gorm.io/gorm"
)

const TableNameRole = "roles"

// Role mapped from table <roles>
type Role struct {
	ID          int64          `json:"id" gorm:"primarykey"`
	Name        string         `json:"name" gorm:"size:50;not null;comment:角色名称"`
	Code        string         `json:"code" gorm:"size:50;unique;not null;comment:角色编码"`
	Status      int64          `json:"status" gorm:"default:1;comment:状态 1:启用 0:禁用"`
	Sort        int64          `json:"sort" gorm:"default:0;comment:排序"`
	Description string         `json:"description" gorm:"size:255;comment:角色描述"`
	CreatedAt   *LocalTime     `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt   *LocalTime     `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"`
	DeletedAt   gorm.DeletedAt `gorm:"column:deleted_at;default:CURRENT_TIMESTAMP" json:"-"`
}

// TableName Role's table name
func (*Role) TableName() string {
	return TableNameRole
}
