// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"gorm.io/gorm"
)

const TableNameSeries = "series"

// Series mapped from table <series>
type Series struct {
	ID              int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name            string         `gorm:"column:name;not null" json:"name" binding:"required"`
	Description     string         `gorm:"column:description" json:"description"`
	FrameMaterialID int64          `gorm:"column:frame_material_id;not null" json:"frame_material_id" binding:"required"`
	FrameMaterial   FrameMaterial  `json:"frame_material" gorm:"foreignKey:FrameMaterialID"`
	PdfURL          string         `gorm:"column:pdf_url;not null" json:"pdf_url" binding:"required"`
	IsNewDesign     bool           `json:"is_new_design" gorm:"default:false"`
	CreatedAt       *LocalTime      `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt       *LocalTime     `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"`
	DeletedAt       gorm.DeletedAt `json:"-" gorm:"index"` // 软删除标志
}

// TableName Series's table name
func (*Series) TableName() string {
	return TableNameSeries
}
