// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"gorm.io/gorm"
)

const TableNameSysUser = "sys_users"

// User mapped from table <users>
type SysUser struct {
	ID        int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Username  string         `gorm:"column:username;not null" json:"username"`
	Email     string         `gorm:"column:email;not null" json:"email"`
	Password  string         `gorm:"column:password;not null" json:"password"`
	Status    int64          `gorm:"column:status;not null" json:"status"`
	CreatedAt *LocalTime      `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt *LocalTime       `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;default:CURRENT_TIMESTAMP" json:"-"`

	SysRoles  []SysRole `gorm:"many2many:sys_user_role;"`  // 多对多关系
}

// TableName User's table name
func (*SysUser) TableName() string {
	return TableNameSysUser
}
