// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"gorm.io/gorm"
)

const TableNameSysPermission = "sys_permissions"

// Permission mapped from table <permissions>
type SysPermission struct {
	ID       int64  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name     string `gorm:"column:name;not null" json:"name"`
	Route    string `gorm:"column:route;" json:"route"`
	Method   string `gorm:"column:method;not null" json:"method"`
	ParentID int64  `gorm:"column:parent_id;default:0" json:"parent_id"`
	//ParentPath  string `gorm:"column:parent_path;not null" json:"parent_path"`
	Description string `gorm:"column:description" json:"description"`

	CreatedAt *LocalTime     `gorm:"autoUpdateTime" json:"created_at"`
	UpdatedAt *LocalTime     `gorm:"autoUpdateTime" json:"updated_at"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;default:CURRENT_TIMESTAMP" json:"-"`

	Children []*SysPermission `json:"children" gorm:"-"` // 子权限列表
}

// TableName Permission's table name
func (*SysPermission) TableName() string {
	return TableNameSysPermission
}
