// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameSysRolePermission = "sys_role_permission"

// RolePermission mapped from table <role_permissions>
type SysRolePermission struct {
	SysRoleID       int64 `gorm:"column:sys_role_id;primaryKey" json:"sys_role_id"`
	SysPermissionID int64 `gorm:"column:sys_permission_id;primaryKey" json:"sys_permission_id"`
}

// TableName RolePermission's table name
func (*SysRolePermission) TableName() string {
	return TableNameSysRolePermission
}
