// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"gorm.io/gorm"
	"time"
)

const TableNameSysRole = "sys_roles"

// Role mapped from table <roles>
type SysRole struct {
	ID          int64  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name        string `gorm:"column:name;not null" json:"name"`
	Description string `gorm:"column:description" json:"description"`

	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
	DeletedAt gorm.DeletedAt `json:"-" gorm:"index"` // 软删除标志

	SysUsers  []SysUser `gorm:"many2many:sys_user_roles;"`
}

// TableName Role's table name
func (*SysRole) TableName() string {
	return TableNameSysRole
}
