// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"gorm.io/gorm"
)

const TableNameUser = "users"

const (
	RoleNormal = 0 // Normal user
	RoleVIP    = 1 // VIP user
)

// User mapped from table <users>
type User struct {
	ID        uint           `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Username  string         `gorm:"column:username;" json:"username"`
	Email     string         `gorm:"column:email;not null" json:"email" binding:"required" validate:"email"`
	Password  string         `gorm:"column:password;not null" json:"password" binding:"required,min=6"`
	Status    int64          `gorm:"column:status;not null;default:0" json:"status" `
	Avatar    string         `gorm:"column:avatar;" json:"avatar"`
	IpAddress string         `gorm:"column:ip_address;" json:"ip_address"`
	CreatedAt *LocalTime     `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt *LocalTime     `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;default:CURRENT_TIMESTAMP" json:"-"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
